const graph = {
  categories: [
    { name: "Country" },
    { name: "City" },
    { name: "Government" },
    { name: "Tourism" },
    { name: "Finance" },
    { name: "Real Estate" },
    { name: "Education" },
    { name: "Oil & Gas" },
    { name: "Healthcare" },
  ],
  nodes: [
    {
      id: "UAE",
      name: "UAE",
      symbolSize: 50,
      x: 0,
      y: 0,
      value: 100,
      category: 0,
    },
    {
      id: "Abu Dhabi",
      name: "Abu Dhabi",
      symbolSize: 40,
      x: -100,
      y: 50,
      value: 80,
      category: 1,
    },
    {
      id: "Dubai",
      name: "Dubai",
      symbolSize: 40,
      x: 100,
      y: 50,
      value: 80,
      category: 1,
    },
    {
      id: "Sharjah",
      name: "Sharjah",
      symbolSize: 30,
      x: 0,
      y: 150,
      value: 60,
      category: 2,
    },
    {
      id: "Ajman",
      name: "Ajman",
      symbolSize: 30,
      x: -150,
      y: -50,
      value: 50,
      category: 2,
    },
    {
      id: "Umm Al Quwain",
      name: "Umm Al Quwain",
      symbolSize: 30,
      x: -50,
      y: -100,
      value: 40,
      category: 2,
    },
    {
      id: "Ras Al Khaimah",
      name: "Ras Al Khaimah",
      symbolSize: 30,
      x: 50,
      y: -100,
      value: 40,
      category: 2,
    },
    {
      id: "Fujairah",
      name: "Fujairah",
      symbolSize: 30,
      x: 100,
      y: -50,
      value: 40,
      category: 2,
    },

    // Abu Dhabi
    {
      id: "Government_Abu Dhabi",
      name: "Government",
      symbolSize: 20,
      x: -120,
      y: 30,
      value: 10,
      category: 3,
    },
    {
      id: "Tourism_Abu Dhabi",
      name: "Tourism",
      symbolSize: 20,
      x: -100,
      y: 20,
      value: 15,
      category: 4,
    },
    {
      id: "Oil_Gas_Abu Dhabi",
      name: "Oil & Gas",
      symbolSize: 20,
      x: -80,
      y: 10,
      value: 10,
      category: 5,
    },
    {
      id: "Real_Estate_Abu Dhabi",
      name: "Real Estate",
      symbolSize: 20,
      x: -60,
      y: 0,
      value: 10,
      category: 6,
    },
    {
      id: "Education_Abu Dhabi",
      name: "Education",
      symbolSize: 20,
      x: -40,
      y: -10,
      value: 15,
      category: 7,
    },
    {
      id: "Healthcare_Abu Dhabi",
      name: "Healthcare",
      symbolSize: 20,
      x: -20,
      y: -20,
      value: 15,
      category: 8,
    },

    // Abu Dhabi: Tourism
    {
      id: "Sheikh Zayed Grand Mosque",
      name: "Sheikh Zayed Grand Mosque",
      symbolSize: 10,
      x: -110,
      y: 10,
      value: 5,
      category: 4,
    },
    {
      id: "Emirates Palace",
      name: "Emirates Palace",
      symbolSize: 10,
      x: -90,
      y: 0,
      value: 5,
      category: 4,
    },
    {
      id: "Louvre Abu Dhabi",
      name: "Louvre Abu Dhabi",
      symbolSize: 10,
      x: -70,
      y: -10,
      value: 5,
      category: 4,
    },
    {
      id: "Ferrari World",
      name: "Ferrari World",
      symbolSize: 10,
      x: -50,
      y: -20,
      value: 5,
      category: 4,
    },
    {
      id: "Yas Island",
      name: "Yas Island",
      symbolSize: 10,
      x: -30,
      y: -30,
      value: 5,
      category: 4,
    },

    // Abu Dhabi: Real Estate
    {
      id: "Al Reem Island",
      name: "Al Reem Island",
      symbolSize: 10,
      x: -50,
      y: 10,
      value: 5,
      category: 6,
    },
    {
      id: "Saadiyat Island",
      name: "Saadiyat Island",
      symbolSize: 10,
      x: -30,
      y: 20,
      value: 5,
      category: 6,
    },
    {
      id: "Al Maryah Island",
      name: "Al Maryah Island",
      symbolSize: 10,
      x: -10,
      y: 30,
      value: 5,
      category: 6,
    },

    // Abu Dhabi: Education
    {
      id: "New York University Abu Dhabi",
      name: "New York University Abu Dhabi",
      symbolSize: 10,
      x: -60,
      y: -20,
      value: 5,
      category: 7,
    },
    {
      id: "Khalifa University",
      name: "Khalifa University",
      symbolSize: 10,
      x: -40,
      y: -30,
      value: 5,
      category: 7,
    },
    {
      id: "University of Sharjah (Abu Dhabi Campus)",
      name: "University of Sharjah (Abu Dhabi Campus)",
      symbolSize: 10,
      x: -20,
      y: -40,
      value: 5,
      category: 7,
    },
    {
      id: "Abu Dhabi University",
      name: "Abu Dhabi University",
      symbolSize: 10,
      x: 0,
      y: -50,
      value: 5,
      category: 7,
    },
    {
      id: "Al Hosn University",
      name: "Al Hosn University",
      symbolSize: 10,
      x: 20,
      y: -60,
      value: 5,
      category: 7,
    },
    {
      id: "Paris-Sorbonne University Abu Dhabi",
      name: "Paris-Sorbonne University Abu Dhabi",
      symbolSize: 10,
      x: 40,
      y: -70,
      value: 5,
      category: 7,
    },

    // Abu Dhabi: Healthcare
    {
      id: "Cleveland Clinic Abu Dhabi",
      name: "Cleveland Clinic Abu Dhabi",
      symbolSize: 10,
      x: -20,
      y: -40,
      value: 5,
      category: 8,
    },
    {
      id: "Sheikh Shakhbout Medical City",
      name: "Sheikh Shakhbout Medical City",
      symbolSize: 10,
      x: 0,
      y: -50,
      value: 5,
      category: 8,
    },
    {
      id: "Abu Dhabi Health Services Company (SEHA)",
      name: "Abu Dhabi Health Services Company (SEHA)",
      symbolSize: 10,
      x: 20,
      y: -60,
      value: 5,
      category: 8,
    },
    {
      id: "NMC Royal Hospital",
      name: "NMC Royal Hospital",
      symbolSize: 10,
      x: 40,
      y: -70,
      value: 5,
      category: 8,
    },
    {
      id: "Mediclinic City Hospital",
      name: "Mediclinic City Hospital",
      symbolSize: 10,
      x: 60,
      y: -80,
      value: 5,
      category: 8,
    },
    {
      id: "Al Zahra Hospital",
      name: "Al Zahra Hospital",
      symbolSize: 10,
      x: 80,
      y: -90,
      value: 5,
      category: 8,
    },
    {
      id: "King’s College Hospital London (Abu Dhabi)",
      name: "King’s College Hospital London (Abu Dhabi)",
      symbolSize: 10,
      x: 100,
      y: -100,
      value: 5,
      category: 8,
    },
    {
      id: "American Hospital Abu Dhabi",
      name: "American Hospital Abu Dhabi",
      symbolSize: 10,
      x: 120,
      y: -110,
      value: 5,
      category: 8,
    },

    // Dubai
    {
      id: "Tourism_Dubai",
      name: "Tourism",
      symbolSize: 20,
      x: 80,
      y: 20,
      value: 15,
      category: 4,
    },
    {
      id: "Finance_Dubai",
      name: "Finance",
      symbolSize: 20,
      x: 100,
      y: 30,
      value: 10,
      category: 5,
    },
    {
      id: "Real_Estate_Dubai",
      name: "Real Estate",
      symbolSize: 20,
      x: 120,
      y: 40,
      value: 10,
      category: 6,
    },
    {
      id: "Healthcare_Dubai",
      name: "Healthcare",
      symbolSize: 20,
      x: 140,
      y: 50,
      value: 15,
      category: 8,
    },

    // Dubai: Tourism
    {
      id: "Burj Khalifa",
      name: "Burj Khalifa",
      symbolSize: 10,
      x: 70,
      y: 10,
      value: 5,
      category: 4,
    },
    {
      id: "Dubai Mall",
      name: "Dubai Mall",
      symbolSize: 10,
      x: 90,
      y: 0,
      value: 5,
      category: 4,
    },
    {
      id: "Burj Al Arab",
      name: "Burj Al Arab",
      symbolSize: 10,
      x: 110,
      y: -10,
      value: 5,
      category: 4,
    },
    {
      id: "Palm Jumeirah",
      name: "Palm Jumeirah",
      symbolSize: 10,
      x: 130,
      y: -20,
      value: 5,
      category: 4,
    },
    {
      id: "Dubai Marina",
      name: "Dubai Marina",
      symbolSize: 10,
      x: 150,
      y: -30,
      value: 5,
      category: 4,
    },
    {
      id: "Global Village",
      name: "Global Village",
      symbolSize: 10,
      x: 170,
      y: -40,
      value: 5,
      category: 4,
    },

    // Dubai: Finance
    {
      id: "Dubai International Financial Centre",
      name: "Dubai International Financial Centre",
      symbolSize: 10,
      x: 110,
      y: 40,
      value: 5,
      category: 5,
    },
    {
      id: "Dubai Financial Market",
      name: "Dubai Financial Market",
      symbolSize: 10,
      x: 130,
      y: 50,
      value: 5,
      category: 5,
    },
    {
      id: "Emirates NBD",
      name: "Emirates NBD",
      symbolSize: 10,
      x: 150,
      y: 60,
      value: 5,
      category: 5,
    },
    {
      id: "Dubai Islamic Bank",
      name: "Dubai Islamic Bank",
      symbolSize: 10,
      x: 170,
      y: 70,
      value: 5,
      category: 5,
    },

    // Dubai: Real Estate
    {
      id: "Emaar Properties",
      name: "Emaar Properties",
      symbolSize: 10,
      x: 140,
      y: 30,
      value: 5,
      category: 6,
    },
    {
      id: "Nakheel Properties",
      name: "Nakheel Properties",
      symbolSize: 10,
      x: 160,
      y: 40,
      value: 5,
      category: 6,
    },
    {
      id: "DAMAC Properties",
      name: "DAMAC Properties",
      symbolSize: 10,
      x: 180,
      y: 50,
      value: 5,
      category: 6,
    },

    // Dubai: Healthcare
    {
      id: "Dubai Healthcare City",
      name: "Dubai Healthcare City",
      symbolSize: 10,
      x: 150,
      y: 20,
      value: 5,
      category: 8,
    },
    {
      id: "American Hospital Dubai",
      name: "American Hospital Dubai",
      symbolSize: 10,
      x: 170,
      y: 30,
      value: 5,
      category: 8,
    },
    {
      id: "Saudi German Hospital",
      name: "Saudi German Hospital",
      symbolSize: 10,
      x: 190,
      y: 40,
      value: 5,
      category: 8,
    },
    {
      id: "Zulekha Hospital",
      name: "Zulekha Hospital",
      symbolSize: 10,
      x: 210,
      y: 50,
      value: 5,
      category: 8,
    },
  ],
  links: [
    { source: "UAE", target: "Abu Dhabi" },
    { source: "UAE", target: "Dubai" },
    { source: "UAE", target: "Sharjah" },
    { source: "UAE", target: "Ajman" },
    { source: "UAE", target: "Umm Al Quwain" },
    { source: "UAE", target: "Ras Al Khaimah" },
    { source: "UAE", target: "Fujairah" },
    { source: "Abu Dhabi", target: "Government_Abu Dhabi" },
    { source: "Abu Dhabi", target: "Tourism_Abu Dhabi" },
    { source: "Abu Dhabi", target: "Oil_Gas_Abu Dhabi" },
    { source: "Abu Dhabi", target: "Real_Estate_Abu Dhabi" },
    { source: "Abu Dhabi", target: "Education_Abu Dhabi" },
    { source: "Abu Dhabi", target: "Healthcare_Abu Dhabi" },
    { source: "Tourism_Abu Dhabi", target: "Sheikh Zayed Grand Mosque" },
    { source: "Tourism_Abu Dhabi", target: "Emirates Palace" },
    { source: "Tourism_Abu Dhabi", target: "Louvre Abu Dhabi" },
    { source: "Tourism_Abu Dhabi", target: "Ferrari World" },
    { source: "Tourism_Abu Dhabi", target: "Yas Island" },
    { source: "Real_Estate_Abu Dhabi", target: "Al Reem Island" },
    { source: "Real_Estate_Abu Dhabi", target: "Saadiyat Island" },
    { source: "Real_Estate_Abu Dhabi", target: "Al Maryah Island" },
    { source: "Education_Abu Dhabi", target: "New York University Abu Dhabi" },
    { source: "Education_Abu Dhabi", target: "Khalifa University" },
    {
      source: "Education_Abu Dhabi",
      target: "University of Sharjah (Abu Dhabi Campus)",
    },
    { source: "Education_Abu Dhabi", target: "Abu Dhabi University" },
    { source: "Education_Abu Dhabi", target: "Al Hosn University" },
    {
      source: "Education_Abu Dhabi",
      target: "Paris-Sorbonne University Abu Dhabi",
    },
    { source: "Healthcare_Abu Dhabi", target: "Cleveland Clinic Abu Dhabi" },
    { source: "Healthcare_Abu Dhabi", target: "Sheikh Shakhbout Medical City" },
    {
      source: "Healthcare_Abu Dhabi",
      target: "Abu Dhabi Health Services Company (SEHA)",
    },
    { source: "Healthcare_Abu Dhabi", target: "NMC Royal Hospital" },
    { source: "Healthcare_Abu Dhabi", target: "Mediclinic City Hospital" },
    { source: "Healthcare_Abu Dhabi", target: "Al Zahra Hospital" },
    {
      source: "Healthcare_Abu Dhabi",
      target: "King’s College Hospital London (Abu Dhabi)",
    },
    { source: "Healthcare_Abu Dhabi", target: "American Hospital Abu Dhabi" },
    { source: "Dubai", target: "Tourism_Dubai" },
    { source: "Dubai", target: "Finance_Dubai" },
    { source: "Dubai", target: "Real_Estate_Dubai" },
    { source: "Dubai", target: "Healthcare_Dubai" },
    { source: "Tourism_Dubai", target: "Burj Khalifa" },
    { source: "Tourism_Dubai", target: "Dubai Mall" },
    { source: "Tourism_Dubai", target: "Burj Al Arab" },
    { source: "Tourism_Dubai", target: "Palm Jumeirah" },
    { source: "Tourism_Dubai", target: "Dubai Marina" },
    { source: "Tourism_Dubai", target: "Global Village" },
    { source: "Finance_Dubai", target: "Dubai International Financial Centre" },
    { source: "Finance_Dubai", target: "Dubai Financial Market" },
    { source: "Finance_Dubai", target: "Emirates NBD" },
    { source: "Finance_Dubai", target: "Dubai Islamic Bank" },
    { source: "Real_Estate_Dubai", target: "Emaar Properties" },
    { source: "Real_Estate_Dubai", target: "Nakheel Properties" },
    { source: "Real_Estate_Dubai", target: "DAMAC Properties" },
    { source: "Healthcare_Dubai", target: "Dubai Healthcare City" },
    { source: "Healthcare_Dubai", target: "American Hospital Dubai" },
    { source: "Healthcare_Dubai", target: "Saudi German Hospital" },
    { source: "Healthcare_Dubai", target: "Zulekha Hospital" },
  ],
};

export default graph;
